//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ActController.rc
//
#define IDS_CONTROLLERS_TAB             1
#define IDS_OPTIONS_TAB                 2
#define IDS_STRING3                     3
#define IDS_VOL                         7
#define IDS_PAN                         8
#define IDS_SEND_N_VOL                  9
#define IDS_SEND_N_PAN                  10
#define IDS_CMD_NONE                    11
#define IDS_CMD_ACT_ENABLE              12
#define IDS_CMD_ACT_LOCK                13
#define IDS_CMD_ACT_LEARN               14
#define IDS_CMD_ROTARIES_MODE           15
#define IDS_CMD_PREV_TRACK              16
#define IDS_CMD_NEXT_TRACK              17
#define IDS_CMD_PREV_TRACK_BANK         18
#define IDS_CMD_NEXT_TRACK_BANK         19
#define IDS_CMD_PREV_STRIP_TYPE         20
#define IDS_CMD_NEXT_STRIP_TYPE         21
#define IDS_CMD_PREV_SEL_TRACK          22
#define IDS_CMD_NEXT_SEL_TRACK          23
#define IDS_CMD_MUTE_SEL_TRACK          24
#define IDS_CMD_SOLO_SEL_TRACK          25
#define IDS_CMD_REC_ARM_SEL_TRACK       26
#define IDS_CMD_PREV_ROTARIES_BANK      27
#define IDS_CMD_NEXT_ROTARIES_BANK      28
#define IDS_CMD_PREV_SLIDERS_BANK       29
#define IDS_CMD_NEXT_SLIDERS_BANK       30
#define IDS_CMD_PREV_BUTTONS_BANK       31
#define IDS_CMD_NEXT_BUTTONS_BANK       32
#define IDS_CMD_PREV_CONTROLLERS_BANK   33
#define IDS_CMD_NEXT_CONTROLLERS_BANK   34
#define IDS_BANK_N                      35
#define IDS_MIDI_LEARN_DDD              36
#define IDS_ON                          37
#define IDS_OFF                         38
#define IDS_MULTI_CHANNEL               39
#define IDS_CHANNEL_STRIP               40
#define IDS_STRIP_PARAMETERS            41
#define IDS_BANK                        42
#define IDS_INPUT_TRIM                  43
#define IDS_STRING44                    44
#define IDS_SYSX_OFN_LIST               44
#define IDS_CMD_AUTO_READ_SEL_TRACK     45
#define IDS_CMD_AUTO_WRITE_SEL_TRACK    46
#define IDS_CMD_PREV_ROTARIES_AND_SLIDERS_BANK 47
#define IDS_CMD_NEXT_ROTARIES_AND_SLIDERS_BANK 48
#define IDS_FONT_NAME                   49
#define IDS_CAPT_JUMP                   50
#define IDS_CAPT_MATCH                  51
#define IDS_CAPT_CONVERGE               52
#define IDS_CMD_PROPS_TOGGLE            53
#define IDS_CMD_PROPS_SHOW              54
#define IDS_CMD_PROPS_HIDE              55
#define IDD_PROPPAGE                    102
#define IDD_TAB1                        130
#define IDD_TAB2                        131
#define IDD_EDIT_LABEL                  133
#define IDD_CELL_MIDI_PROPS             135
#define IDD_MIDI_INIT                   136
#define IDS_CMD_OPEN_CUR_FX             137
#define IDS_CMD_CLOSE_CUR_FX            138
#define IDS_CMD_FOCUS_NEXT_FX           139
#define IDS_CMD_FOCUS_PREV_FX           140
#define IDS_CMD_OPEN_NEXT_FX            141
#define IDS_CMD_OPEN_PREV_FX            142
#define IDC_BUTTON_SELECT               1000
#define IDC_BUTTON_ACTION               1001
#define IDC_BUTTON_EXCLUDE_ACT          1002
#define IDC_R1_NAME                     1003
#define IDC_BUTTON_BANK                 1003
#define IDC_R2_NAME                     1004
#define IDC_KNOBS_BANK                  1004
#define IDC_R3_NAME                     1005
#define IDC_SLIDERS_BANK                1005
#define IDC_R4_NAME                     1006
#define IDC_R5_NAME                     1007
#define IDC_R6_NAME                     1008
#define IDC_R7_NAME                     1009
#define IDC_R8_NAME                     1010
#define IDC_R1_VALUE                    1011
#define IDC_R2_VALUE                    1012
#define IDC_R3_VALUE                    1013
#define IDC_R4_VALUE                    1014
#define IDC_R5_VALUE                    1015
#define IDC_R6_VALUE                    1016
#define IDC_R7_VALUE                    1017
#define IDC_R8_VALUE                    1018
#define IDC_S1_NAME                     1019
#define IDC_S2_NAME                     1020
#define IDC_S3_NAME                     1021
#define IDC_S4_NAME                     1022
#define IDC_S5_NAME                     1023
#define IDC_S6_NAME                     1024
#define IDC_S7_NAME                     1025
#define IDC_S8_NAME                     1026
#define IDC_S1_VALUE                    1027
#define IDC_S2_VALUE                    1028
#define IDC_S3_VALUE                    1029
#define IDC_S4_VALUE                    1030
#define IDC_S5_VALUE                    1031
#define IDC_S6_VALUE                    1032
#define IDC_S7_VALUE                    1033
#define IDC_S8_VALUE                    1034
#define IDC_ACT_ENABLE                  1035
#define IDC_ACTIVE_ROTARY_BANK          1035
#define IDC_ACT_LOCK                    1036
#define IDC_ACTIVE_SLIDER_BANK          1036
#define IDC_ACT_NAME                    1037
#define IDC_ACTIVE_BUTTON_BANK          1037
#define IDC_B1_NAME                     1038
#define IDC_B2_NAME                     1039
#define IDC_B3_NAME                     1040
#define IDC_B4_NAME                     1041
#define IDC_B5_NAME                     1042
#define IDC_B6_NAME                     1043
#define IDC_B7_NAME                     1044
#define IDC_B8_NAME                     1045
#define IDC_B1_VALUE                    1046
#define IDC_B2_VALUE                    1047
#define IDC_B3_VALUE                    1048
#define IDC_B4_VALUE                    1049
#define IDC_B5_VALUE                    1050
#define IDC_B6_VALUE                    1051
#define IDC_B7_VALUE                    1052
#define IDC_B8_VALUE                    1053
#define IDC_SB1_NAME                    1054
#define IDC_SB2_NAME                    1055
#define IDC_SB3_NAME                    1056
#define IDC_SB4_NAME                    1057
#define IDC_SB5_NAME                    1058
#define IDC_SB6_NAME                    1059
#define IDC_SB7_NAME                    1060
#define IDC_SB8_NAME                    1061
#define IDC_SB1_VALUE                   1062
#define IDC_SB2_VALUE                   1063
#define IDC_SB3_VALUE                   1064
#define IDC_SB4_VALUE                   1065
#define IDC_SB5_VALUE                   1066
#define IDC_SB6_VALUE                   1067
#define IDC_SB7_VALUE                   1068
#define IDC_SB8_VALUE                   1069
#define IDC_EXCLUDE_ROTARIES_ACT        1070
#define IDC_EXCLUDE_SLIDERS_ACT         1071
#define IDC_TAB_CTRL                    1072
#define IDC_GROUP_TRACK                 1074
#define IDC_GROUP_BUS                   1075
#define IDC_GROUP_MAIN                  1076
#define IDC_MULTI_CHANNEL               1077
#define IDC_CHANNEL_STRIP               1078
#define IDC_KNOBS_BINDING               1079
#define IDC_SLIDERS_BINDING             1080
#define IDC_R1_LABEL                    1080
#define IDC_R2_LABEL                    1081
#define IDC_KNOBS_CAPTMODE              1081
#define IDC_R3_LABEL                    1082
#define IDC_SLIDERS_CAPTMODE            1082
#define IDC_R4_LABEL                    1083
#define IDC_KNOBS_MIDI_INTERPRET        1083
#define IDC_R5_LABEL                    1084
#define IDC_R6_LABEL                    1085
#define IDC_R7_LABEL                    1086
#define IDC_R8_LABEL                    1087
#define IDC_S1_LABEL                    1088
#define IDC_S2_LABEL                    1089
#define IDC_S3_LABEL                    1090
#define IDC_S4_LABEL                    1091
#define IDC_S5_LABEL                    1092
#define IDC_S6_LABEL                    1093
#define IDC_S7_LABEL                    1094
#define IDC_S8_LABEL                    1095
#define IDC_SB1_LABEL                   1096
#define IDC_SB2_LABEL                   1097
#define IDC_SB3_LABEL                   1098
#define IDC_SB4_LABEL                   1099
#define IDC_SB5_LABEL                   1100
#define IDC_SB6_LABEL                   1101
#define IDC_SB7_LABEL                   1102
#define IDC_SB8_LABEL                   1103
#define IDC_B1_LABEL                    1104
#define IDC_B2_LABEL                    1105
#define IDC_B3_LABEL                    1106
#define IDC_B4_LABEL                    1107
#define IDC_B5_LABEL                    1108
#define IDC_B6_LABEL                    1109
#define IDC_B7_LABEL                    1110
#define IDC_B8_LABEL                    1111
#define IDC_SELECT_HIGHLIGHTS_TRACK     1112
#define IDC_ROTARY_BANK_LABEL           1112
#define IDC_LABEL                       1113
#define IDC_SLIDER_BANK_LABEL           1113
#define IDC_ACT_FOLLOWS_CONTEXT         1114
#define IDC_BUTTON_BANK_LABEL           1114
#define IDC_MIDI_LEARN_SHIFT            1115
#define IDC_DEFAULTS                    1116
#define IDC_COMMETS                     1122
#define IDC_RESET_MIDI_LEARN            1123
#define IDC_RAD_INTERPRET               1127
#define IDC_RAD1_INTERPRET              1128
#define IDC_CENTER_VAL                  1130
#define IDC_USE_ACCEL                   1131
#define IDC_STATUS                      1132
#define IDC_NUM                         1133
#define IDC_VALUE                       1134
#define IDC_SYSEX_STRING                1135
#define IDC_SEND                        1136
#define IDC_EDIT_INIT                   1137
#define IDC_LOAD_SYSEX                  1140
#define IDC_CLEAR_SYSEX                 1141

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1142
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
