//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ControlSurfaceProbe.rc
//
#define IDD_PROPPAGE                    102
#define IDD_CAPABILITIES                130
#define IDC_MIX_STRIP                   1000
#define IDC_STRIP_NUM                   1001
#define IDC_MIX_PARAM                   1002
#define IDC_PARAM_NUM                   1003
#define IDC_MIX_VALUE                   1004
#define IDC_MIX_VALUE_LABEL             1005
#define IDC_MIX_VALUE_TEXT              1006
#define IDC_STRIP_NUM_SPIN              1007
#define IDC_PARAM_NUM_SPIN              1008
#define IDC_UPDATE_COUNT                1009
#define IDC_STRIP_NAME                  1010
#define IDC_NUM_MAINS                   1011
#define IDC_NUM_TRACKS                  1012
#define IDC_NUM_AUXS                    1013
#define IDC_MIX_NEW_VAL                 1014
#define IDC_MIX_SEND                    1015
#define IDC_TS_AUDIO                    1016
#define IDC_TS_PLAY                     1017
#define IDC_TS_SCRUB                    1018
#define IDC_TS_REC                      1019
#define IDC_TS_REC_AUTO                 1020
#define IDC_TS_LOOP                     1021
#define IDC_NUM_BUSES                   1022
#define IDC_NUM_MASTER                  1023
#define IDC_MIX_VALUE_ARM               1024
#define IDC_MIX_ARM                     1025
#define IDC_MIX_DISARM                  1026
#define IDC_PARAM_NUM_HIGH              1027
#define IDC_PARAM_NUM_LOW               1028
#define IDC_PARAM_NUM_SPIN_HIGH         1029
#define IDC_PARAM_NUM_SPIN_LOW          1030
#define IDC_TS_AUDIO_SET                1031
#define IDC_TS_AUDIO_CLEAR              1032
#define IDC_COMMANDS                    1033
#define IDC_DO_COMMAND                  1034
#define IDC_UNIQUE_ID                   1035
#define IDC_HOST_VERSION                1036
#define IDC_TS_PLAY_SET                 1037
#define IDC_TS_PLAY_CLEAR               1038
#define IDC_TS_SCRUB_SET                1039
#define IDC_TS_SCRUB_CLEAR              1040
#define IDC_TS_REC_SET                  1041
#define IDC_TS_REC_CLEAR                1042
#define IDC_TS_REC_AUTO_SET             1043
#define IDC_TS_REC_AUTO_CLEAR           1044
#define IDC_TS_LOOP_SET                 1045
#define IDC_TS_LOOP_CLEAR               1046
#define IDC_HOST_NAME                   1047
#define IDC_CAPABILITIES                1048
#define IDC_TS_AUTOPUNCH                1049
#define IDC_TS_AUTOPUNCH_SET            1050
#define IDC_TS_AUTOPUNCH_CLEAR          1051
#define IDC_STRIP_NUM_METERS            1052
#define IDC_STRIP_METER_VALUES          1053
#define IDC_MARKER_COUNT                1054
#define IDC_UPDATE_MARKER_LIST          1055
#define IDC_MARKER_LIST                 1056
#define IDC_MARKER_MEASURES             1057
#define IDC_MARKER_BEATS                1058
#define IDC_MARKER_TICKS                1059
#define IDC_MARKER_GET_NEAREST          1060
#define IDC_MARKER_THE_NEAREST          1061
#define IDC_MARKER_MEAS_SPIN            1062
#define IDC_MARKER_TICK_SPIN            1063
#define IDC_MARKER_BEAT_SPIN            1064
#define IDC_SCT_SWITCH                  1065
#define IDC_SCT_ROTARY                  1066
#define IDC_SCT_SLIDER                  1067
#define IDC_SCT_ROTARY_CAPTION          1068
#define IDC_SCT_SWITCH_CAPTION          1069
#define IDC_SCT_SLIDER_CAPTION          1070
#define IDC_MAP_NAME                    1071
#define IDC_SCT_ROTARY2                 1072
#define IDC_SCT_ROTARY_CAPTION2         1073
#define IDC_SCT_ROTARY3                 1074
#define IDC_SCT_ROTARY_CAPTION3         1075
#define IDC_SCT_ROTARY4                 1076
#define IDC_SCT_ROTARY_CAPTION4         1077
#define IDC_SCT_SLIDER_CAPTION2         1078
#define IDC_SCT_SLIDER2                 1079
#define IDC_SCT_SLIDER_CAPTION3         1080
#define IDC_SCT_SLIDER3                 1081
#define IDC_SCT_SLIDER_CAPTION4         1082
#define IDC_SCT_SLIDER4                 1083
#define IDC_CHECK1                      1084
#define IDC_LOCK_CONTEXT                1084
#define IDC_READ_ENABLE                 1085
#define IDC_CHECK3                      1086
#define IDC_MAP_                        1086
#define IDC_UI_CONTEXT                  1086
#define IDC_CHECK2                      1087
#define IDC_LEARN_ENABLE                1087
#define IDC_WND_TYPE                    1088
#define IDC_WND_OPEN                    1089
#define IDC_WND_CLOSE                   1090
#define IDC_WND_MIN                     1091
#define IDC_WND_ZOOM_RIGHT2             1092
#define IDC_WND_ZOOM_RIGHT              1093
#define IDC_WND_ZOOM_LEFT2              1094
#define IDC_WND_ZOOM_LEFT               1095
#define IDC_WND_STATE                   1096
#define IDC_WND_ZOOM_UP                 1098
#define IDC_WND_ZOOM_DOWN               1099
#define IDC_WND_ZOOM_UP2                1100
#define IDC_WND_ZOOM_DOWN2              1101
#define IDC_BUTTON8                     1102
#define IDC_WND_SCROLL_RIGHT2           1102
#define IDC_WND_SCROLL_RIGHT            1103
#define IDC_WND_SCROLL_LEFT2            1104
#define IDC_WND_SCROLL_LEFT             1105
#define IDC_WND_SCROLL_UP               1106
#define IDC_WND_SCROLL_DOWN             1107
#define IDC_WND_SCROLL_UP2              1108
#define IDC_WND_SCROLL_DOWN2            1109

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
