#pragma once

////////////////////////////////////////////////////////////////////////////////
// The following is a list of commands supported thru ISonarCommands.
//
// This list is subject to change according to the policy described:
//	As commands are added in SONAR, new ID's are added at the bottom
// of this list.
// When commands are deprecated in SONAR, the location in this list of ID's
// is preserved and marked as "RESERVED" so that other commands do not shift.
// Thus, invoking a particular command ID is not guaranteed to work in future
// releases.
////////////////////////////////////////////////////////////////////////////////

typedef enum SONAR_COMMAND_IDS
{
	CMD_FILE_NEW_TEMPLATE = 1,
	CMD_FILE_OPEN,
	CMD_FILE_SAVE,
	CMD_FILE_SAVE_AS,
	CMD_RESERVED1,
	CMD_RESERVED2,
	CMD_FILE_PRINT_PREVIEW,
	CMD_FILE_PRINT,
	CMD_FILE_PRINT_SETUP,
	CMD_APP_EXIT,
	CMD_APP_ABOUT,
	CMD_FILE_MRU_FILE1,
	CMD_FILE_MRU_FILE2,
	CMD_FILE_MRU_FILE3,
	CMD_FILE_MRU_FILE4,
	CMD_REALTIME_PLAY,
	CMD_REALTIME_RECORD,
	CMD_REALTIME_REW,
	CMD_REALTIME_STEP_RECORD,
	CMD_REALTIME_RECORD_MODE,
	CMD_REALTIME_REJECT_LOOP_TAKE,
	CMD_REALTIME_AUTO_SHUTTLE,
	CMD_RESERVED3,
	CMD_RESERVED4,
	CMD_RESERVED5,
	CMD_FROM_EQ_NOW,
	CMD_THRU_EQ_NOW,
	CMD_FROM_EQ_START,
	CMD_THRU_EQ_END,
	CMD_SELECT_ALL,
	CMD_SELECT_NONE,
	CMD_GOTO_TIME,
	CMD_GOTO_FROM,
	CMD_GOTO_THRU,
	CMD_GOTO_START,
	CMD_GOTO_END,
	CMD_GOTO_PREV_MEAS,
	CMD_GOTO_NEXT_MEAS,
	CMD_SEARCH,
	CMD_SEARCH_NEXT,
	CMD_EDIT_UNDO,
	CMD_EDIT_COPY,
	CMD_EDIT_CUT,
	CMD_EDIT_PASTE,
	CMD_RESERVED6,
	CMD_EDIT_QUANTIZE,
	CMD_EDIT_INTERPOLATE,
	CMD_EDIT_LENGTH,
	CMD_EDIT_SLIDE,
	CMD_EDIT_RETROGRADE,
	CMD_EDIT_TRANSPOSE,
	CMD_EDIT_FIT_TO_TIME,
	CMD_EDIT_FIT_IMPROV,
	CMD_EDIT_RUN_CAL,
	CMD_INSERT_CONTROLLER_SERIES,
	CMD_TRACK_NAME,
	CMD_TRACK_MUTE,
	CMD_TRACK_ARCHIVE,
	CMD_RESERVED7,
	CMD_TRACK_TIME,
	CMD_TRACK_KEY,
	CMD_TRACK_VEL,
	CMD_TRACK_PORT,
	CMD_TRACK_CHAN,
	CMD_TRACK_PATCH,
	CMD_TRACK_VOL,
	CMD_TRACK_PAN,
	CMD_TRACK_CLONE,
	CMD_RESERVED8,
	CMD_TRACK_WIPE,
	CMD_TRACK_SORT,
	CMD_TRACK_SOLO,
	CMD_TRACK_UNSOLO,
	CMD_VIEW_NEW_EVENT_LIST,
	CMD_VIEW_NEW_PIANO_ROLL,
	CMD_VIEW_NEW_STAFF,
	CMD_RESERVED9,
	CMD_RESERVED10,
	CMD_RESERVED11,
	CMD_RESERVED12,
	CMD_RESERVED13,
	CMD_RESERVED14,
	CMD_RESERVED15,
	CMD_WINDOW_TILE_HORZ,
	CMD_WINDOW_TILE_VERT,
	CMD_WINDOW_CASCADE,
	CMD_RESERVED16,
	CMD_WINDOW_ARRANGE,
	CMD_OPTIONS,
	CMD_RESERVED17,
	CMD_RESERVED18,
	CMD_RESERVED19,
	CMD_RESERVED20,
	CMD_GLOBAL_OPTIONS,
	CMD_RESERVED21,
	CMD_RESERVED22,
	CMD_RESERVED23,
	CMD_MIDI_PORTS,
	CMD_RESERVED24,
	CMD_BINDINGS,
	CMD_INIFILES,
	CMD_COLORS,
	CMD_VIEW_TEMPO,
	CMD_VIEW_METER,
	CMD_VIEW_MARKERS,
	CMD_VIEW_CONSOLE,
	CMD_VIEW_PLAYLIST,
	CMD_VIEW_SYSX,
	CMD_VIEW_CAL,
	CMD_REALTIME_PATCH_CACHE,
	CMD_EDIT_SCALE_VELOCITY,
	CMD_RESERVED25,
	CMD_REALTIME_PANIC,
	CMD_RESERVED26,
	CMD_RESERVED27,
	CMD_RESERVED28,
	CMD_RESERVED29,
	CMD_INSERT_BANK_PATCH,
	CMD_INSERT_WAVE,
	CMD_INSERT_TEMPO,
	CMD_INSERT_METER,
	CMD_RESERVED30,
	CMD_INSERT_TEMPO_SERIES,
	CMD_EDIT_GROOVE_QUANTIZE,
	CMD_FILE_INFO,
	CMD_TRACK_BANK,
	CMD_VIEW_NEW_LYRICS,
	CMD_VIEW_BIG_TIME,
	CMD_RESERVED31,
	CMD_AUDIO_REVERSE,
	CMD_AUDIO_REMOVE_SILENCE,
	CMD_AUDIO_EXTRACT_TIMING,
	CMD_AUDIO_LOUDER,
	CMD_AUDIO_SOFTER,
	CMD_AUDIO_NORMALIZE,
	CMD_AUDIO_FADE,
	CMD_AUDIO_XFADE,
	CMD_AUDIO_GRAPHIC_EQ,
	CMD_AUDIO_PARAMETRIC_EQ,
	CMD_AUDIO_SPLIT,
	CMD_RESERVED32,
	CMD_SELECT_FILTER,
	CMD_SELECT_TIME,
	CMD_AUDIO_COMPACT,
	CMD_AUDIO_CLEAN,
	CMD_RESERVED33,
	CMD_VIEW_NEW_AUDIO,
	CMD_RESERVED34,
	CMD_AUDIO_OPTIONS,
	CMD_VIEW_LAYOUTS,
	CMD_INSERT_MARKER,
	CMD_EDIT_REDO,
	CMD_RESERVED35,
	CMD_VIEW_NEW_PANEL,
	CMD_REALTIME_TEMPO1,
	CMD_REALTIME_TEMPO2,
	CMD_REALTIME_TEMPO3,
	CMD_VIEW_EFFECTS,
	CMD_RESERVED36,
	CMD_RESERVED37,
	CMD_VIRTUAL_PIANO,
	CMD_SOUND_FONTS,
	CMD_FILE_SEND,
	CMD_EDIT_DELETE,
	CMD_CREATE_CLIPS,
	CMD_AUDIO_HARDWARE,
	CMD_AUDIO_PITCH_DETECT,
	CMD_MARKER_PREVIOUS,
	CMD_MARKER_NEXT,
	CMD_REALTIME_STOP,
	CMD_TRACK_SOURCES,
	CMD_TRACK_ARM,
	CMD_FILE_CLOSE,
	CMD_EDIT_HISTORY,
	CMD_INSERT_TIME,
	CMD_INSTRUMENTS,
	CMD_VIEW_TOOLBAR_STANDARD,
	CMD_VIEW_TOOLBAR_LOOP,
	CMD_VIEW_TOOLBAR_MARKERS,
	CMD_VIEW_TOOLBAR_POSITION,
	CMD_VIEW_TOOLBAR_RECORD,
	CMD_VIEW_TOOLBAR_SELECT,
	CMD_VIEW_TOOLBAR_SYNC,
	CMD_VIEW_TOOLBAR_TEMPO,
	CMD_VIEW_TOOLBAR_TRANSPORT,
	CMD_VIEW_CONTROLBAR_TRANSPORT,
	CMD_VIEW_TOOLBAR_VIEWS,
	CMD_HELP_FINDER,
	CMD_HELP_README,
	CMD_HELP_QUICKSTART,
	CMD_TIP_OF_THE_DAY,
	CMD_HELP_WEB,
	CMD_VIEW_VIDEO,
	CMD_INSERT_VIDEO,
	CMD_VIDEO_EXPORT,
	CMD_AUDIO_MIXDOWN_BOUNCE,
	CMD_CHANGE_AUDIO_FORMAT,
	CMD_AUDIO_MIXDOWN_EXPORT,
	CMD_RESERVED38,
	CMD_RESERVED39,
	CMD_RESERVED40,
	CMD_RESERVED41,
	CMD_RESERVED42,
	CMD_RESERVED43,
	CMD_RESERVED44,
	CMD_RESERVED45,
	CMD_RESERVED46,
	CMD_RESERVED47,
	CMD_RESERVED48,
	CMD_RESERVED49,

	// TODO: maybe remove from this point forward
	CMD_TRACK_PROPERTIES,				
	CMD_RULER_MBT,							// options menu
	CMD_RULER_HMSF,							// options menu
	CMD_RULER_SAMPLE,						// options menu
	CMD_SET_LOOP_FROM_SELECTION,	
	CMD_SELECT_LOOP_REGION,		
	CMD_LOOP_TOGGLE,					
	CMD_SET_PUNCH_FROM_SELECTION,
	CMD_SELECT_PUNCH_REGION,		
	CMD_SET_SNAPPING,				
	CMD_CLIPS_VIEW_OPTIONS,		
	CMD_DRAG_OPTIONS,				
	CMD_CLIP_PROPERTIES,
	CMD_CREATE_VOLUME_ENVELOPE,
	CMD_CREATE_PAN_ENVELOPE,
	CMD_SHOW_ALL_ENVELOPES,
	CMD_HIDE_ALL_ENVELOPES,
	CMD_SHOW_ALL_VOLUME_ENVELOPES,
	CMD_SHOW_ALL_PAN_ENVELOPES,
	CMD_SHOW_ALL_PLUGIN_ENVELOPES,
	CMD_SHOW_ALL_AUTOMATED_MUTE_ENVELOPES,
	CMD_SHOW_ALL_MIDI_ENVELOPES,
	CMD_BOUNCE_TO_CLIPS,					// Edit Menu
	CMD_INSERT_AUDIO_TRACK,			   // Insert menu
	CMD_INSERT_MIDI_TRACK,				// Insert Menu
	CMD_APPLY_AUDIO_FX,					// Edit menu
	CMD_APPLY_MIDI_FX,						// Edit menu
	CMD_SPLIT_CLIPS,						// Edit menu
	CMD_EDIT_APPLY_TRIMMING,				// Edit menu
	CMD_SELECT_TRACK_ENVELOPES_WITH_CLIPS, // Edit menu
	CMD_VIEW_NEW_LOOP_CONSTR,			// VIEW MENU
	CMD_VIEW_NEW_EXPLORER,				// VIEW MENU
	CMD_VIEW_PEAVEY,						// VIEW MENU
	CMD_VIEW_TOOLBARS,						// VIEW MENU
	CMD_REALTIME_RECORD_AUTOMATION,	// Transport menu
	CMD_RESERVED50,
	CMD_TRACK_ARM_AUTOMATION,			// Track menu
	CMD_DELETE_TRACK,						// Track menu
	CMD_TRACK_HIDE,							// Track menu
	CMD_RECORD_VU,							// Track menu
	CMD_PLAYBACK_VU,						// Help menu
	CMD_KEYBOARD_SHORTCUTS,				// Help menu
	CMD_SONAR_UPD_URL,						// Help menu
	CMD_SONAR_FAQ_URL,						// Help menu
	CMD_SONAR_SUPPORT_URL,				// Help menu
	CMD_SONAR_NEWSGROUPS_URL,			// Help menu
	CMD_SONAR_URL,							// Help menu
	CMD_UNLINK_CLIPS,
	CMD_SELECT_SIBLINGS,
	CMD_CLIPS_TOGGLE_LOOPING,			// Edit Menu
	CMD_SMARTCLIP_INC_PITCH,
	CMD_SMARTCLIP_DEC_PITCH,
	CMD_REALTIME_AUDIO_RUNNING,		// Transport Menu
	CMD_SHOW_HIDE_TRACKS,
	CMD_AUTO_CROSSFADE,
	CMD_SET_SNAP_OFFSET_TO_NOW_TIME,
	CMD_AUTOMATION_STATIC_MODE,
	CMD_RESERVED51,
	CMD_RESERVED52,
	CMD_RESERVED53,
	CMD_PROJECT_FILES,					// File Menu
	CMD_DRUMMAP_MGR,						// Drum Map Magager
	CMD_SHOW_ALL_AUX_SEND_ENVELOPES,
	CMD_VIEW_SYNTH_RACK,
	CMD_METRONOME_PLAYBACK,				// Metronome toolbar
	CMD_METRONOME_RECORD,

	CMD_REALTIME_SYNC_INTERNAL,		// Sync toolbar
	CMD_REALTIME_SYNC_MIDI,
	CMD_REALTIME_SYNC_SMPTE,
	CMD_REALTIME_SYNC_AUDIO,
	CMD_REALTIME_SYNC_TX_MMC,

	CMD_PLAY_IN_MONO,						// Playback state toolbar

	CMD_AUTOMATION_SNAPSHOT,			// Automation toolbar
	CMD_AUTOMATION_UNARM_ALL,
	CMD_AUTOMATION_LIVE_MODE,

	// SONAR 2.1
	CMD_EDIT_ENABLE_MIDI_CROPPING,	// Options menu
	CMD_EXPORT_OMF,						// File | Export

	// SONAR 3
	CMD_TRACK_INPUT_MONITOR,
	CMD_REALTIME_SYNC_TX_MIDI,			// Sync Toolbar
	CMD_REALTIME_SYNC_TX_MTC,			// Sync Toolbar
}
SONAR_COMMAND_ID;
